### ISSUE TITLE
Forecasting with long output dimension

### ISSUE THREAD

**Issue by linotto** [cchallu/nbeatsx#6]
Hello, 

First of all thank you for your paper, I have tried N-beatx and it's performing super well. 

The problem is that I need to forecast not only Day-Ahead but seven days (so 168 hours) . I tried to put my data in daily and did a 7 forecast horizon but its not good, do you have any advice to try for that problem please ? I would be very thanksful. 

(By the way, my data is similar to yours in your n-beatsx paper. 

Thank you for your time

**Comment by kdgutier** [comment]
Hi @linotto, we recently published a paper on the long-horizon forecasting topic

And released the implementation of a new method built on top of N-BEATS that we called N-HiTS.
The paper is here: https://arxiv.org/abs/2201.12886
The code is here: https://github.com/Nixtla/neuralforecast

We have not yet tested the N-HiTSx code, but in principle one could just try it now.
We are interested in your experience with it.

Greetings
