### ISSUE TITLE
FCNN realization doesn't take exogenous variables as arguments

### ISSUE THREAD

**Issue by MBelniak** [cchallu/nbeatsx#9]
Hi,

In the paper in eq. (1) it is stated, that FCNN in each block is a function of output of previous block/stack (y^{back}) + exogenous variables. Whereas, I see at https://github.com/cchallu/nbeatsx/blob/main/src/nbeats/nbeats_model.py#L122 that there's only y^{back} passed to FCNN. My question is: why is that? My reasoning for passing insample exog. variables as well is that they could provide additional information on how to scale the C_{s,l} context vector later on.

**Comment by kdgutier** [comment]
Hi @MBelniak,

Thanks for the comment. For the moment scaling is done independently from the model. 
By the [transform_data](https://github.com/cchallu/nbeatsx/blob/main/src/utils/experiment/utils_experiment.py#L23) and the  [Scaler Class](https://github.com/cchallu/nbeatsx/blob/fe116d21785fca55670d258756e7c35fcb613eca/src/utils/data/utils.py#L14).

We agree that insample exogenous variables could benefit by simplifying the neural forecasting pipeline, to help scale the features. That is still an open research question.

**Comment by MBelniak** [comment]
Thanks. I didn't exactly mean "scaling the features", but producing thetas, which in fact "scale" the C_{s,l,i} vector, but as I understand it's just an open question.
